#include<stdio.h>
#include<conio.h>
#include<graphics.h>

//#include"mouse1.cpp"

//unsigned int *gp,*ga,g=0;

one(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(237,236,".");
	return 0;
}

two(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(232,231,".");
	outtextxy(242,241,".");
	return 0;
}

three(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(237,236,".");
	outtextxy(232,231,".");
	outtextxy(242,241,".");
	return 0;
}

four(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(232,231,".");
	outtextxy(242,241,".");
	outtextxy(242,231,".");
	outtextxy(232,241,".");
	return 0;
}

five(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(237,236,".");
	outtextxy(232,231,".");
	outtextxy(242,241,".");
	outtextxy(242,231,".");
	outtextxy(232,241,".");
	return 0;
}

six(void)
{
	setfillstyle(1,WHITE);
	bar3d(225,225,255,255,0,0);
	outtextxy(232,236,".");
	outtextxy(242,236,".");
	outtextxy(232,231,".");
	outtextxy(242,241,".");
	outtextxy(242,231,".");
	outtextxy(232,241,".");
	return 0;
}




